### ISSUE TITLE
Info windows on markers

### ISSUE THREAD

**Issue by lomholdt** [instantsearch/instantsearch-googlemaps#6] opened 2016-03-24 18:43 UTC
As a developer I would like to be able to add a template for info windows for the markers on the map (https://developers.google.com/maps/documentation/javascript/examples/infowindow-simple).

**Comment by vvo** [comment] 2016-03-31 21:07
Hi Jonas, thanks for taking the time to give us feedback.

Would you like to contribute to this project? This is only wrapping https://github.com/tomchentw/react-google-maps

**Comment by vvo** [comment] 2016-04-14 09:52
duplicate of #3

**Closed as completed by vvo** 2016-04-14 09:52 UTC
